on:
    push:
        branches: [main, demo, staging]
    pull_request:
        branches: [main, demo, staging]

name: ðŸš€ Deploy website on push

jobs:
    web-deploy:
        name: ðŸŽ‰ Deploy to ${{ matrix.environment }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                include:
                    # Production Environment
                    - branch: main
                      environment: production
                      api_base_url: https://cookds.servicore.io/backend
                      app_url: https://cookds.servicore.io
                      stripe_key_secret: STRIPE_KEY
                      ftp_server_secret: FTP_SERVER
                      ftp_username_secret: FTP_USERNAME
                      ftp_password_secret: FTP_PASSWORD

                    # Demo Environment
                    - branch: demo
                      environment: demo
                      api_base_url: https://demo.servicore.io/backend
                      app_url: https://demo.servicore.io
                      stripe_key_secret: STRIPE_KEY_DEMO
                      ftp_server_secret: FTP_SERVER_DEMO
                      ftp_username_secret: FTP_USERNAME_DEMO
                      ftp_password_secret: FTP_PASSWORD_DEMO

                    # Demo Environment
                    - branch: staging
                      environment: staging
                      api_base_url: https://staging.servicore.io/backend
                      app_url: https://staging.servicore.io
                      stripe_key_secret: STRIPE_KEY_DEMO
                      ftp_server_secret: FTP_SERVER_STAGING
                      ftp_username_secret: FTP_USERNAME_STAGING
                      ftp_password_secret: FTP_PASSWORD_STAGING

        steps:
            - name: ðŸšš Get latest code
              if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', matrix.branch)
              uses: actions/checkout@v2

            - name: ðŸ“¦ Build Vue app for ${{ matrix.environment }}
              if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', matrix.branch)
              run: |
                  npm install
                  npm run build
              env:
                  VITE_API_BASE_URL: ${{ matrix.api_base_url }}
                  VITE_APP_URL: ${{ matrix.app_url }}
                  VITE_STRIPE_KEY: ${{ secrets[matrix.stripe_key_secret] }}

            - name: ðŸ“‚ Sync frontend build to ${{ matrix.environment }}
              if: github.event_name == 'push' && github.ref == format('refs/heads/{0}', matrix.branch)
              uses: SamKirkland/FTP-Deploy-Action@v4.3.5
              with:
                  server: ${{ secrets[matrix.ftp_server_secret] }}
                  username: ${{ secrets[matrix.ftp_username_secret] }}
                  password: ${{ secrets[matrix.ftp_password_secret] }}
                  protocol: ftps
                  port: 21
                  security: loose
                  timeout: 120000
                  local-dir: ./dist/
                  server-dir: /
                  exclude: |
                      backend/**
                  dangerous-clean-slate: false
